[package]
name = "cadmark-bridge"
version.workspace = true
edition = "2024"

[dependencies]
cadmark-core = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
base64 = "0.22.1"
