import importlib as _cadmark_importlib
import importlib.metadata as _cadmark_metadata
import inspect as _cadmark_inspect
import sys as _cadmark_sys

import OCP as _cadmark_ocp
import build123d as _cadmark_build123d
from OCP.BRepAlgoAPI import (
    BRepAlgoAPI_Common as _cadmark_expected_common,
    BRepAlgoAPI_Cut as _cadmark_expected_cut,
    BRepAlgoAPI_Fuse as _cadmark_expected_fuse,
    BRepAlgoAPI_Splitter as _cadmark_expected_splitter,
)
from OCP.BRepBuilderAPI import (
    BRepBuilderAPI_Copy as _cadmark_expected_copy,
    BRepBuilderAPI_GTransform as _cadmark_expected_gtransform,
    BRepBuilderAPI_Transform as _cadmark_expected_transform,
)
from OCP.BRepFeat import BRepFeat_MakeDPrism as _cadmark_expected_dprism
from OCP.BRepFilletAPI import (
    BRepFilletAPI_MakeChamfer as _cadmark_expected_chamfer,
    BRepFilletAPI_MakeFillet as _cadmark_expected_fillet,
)
from OCP.BRepOffset import BRepOffset_MakeOffset as _cadmark_expected_offset
from OCP.BRepOffsetAPI import (
    BRepOffsetAPI_DraftAngle as _cadmark_expected_draft,
    BRepOffsetAPI_MakePipeShell as _cadmark_expected_pipe,
    BRepOffsetAPI_MakeThickSolid as _cadmark_expected_thick,
    BRepOffsetAPI_ThruSections as _cadmark_expected_loft,
)
from OCP.BRepPrimAPI import (
    BRepPrimAPI_MakeBox as _cadmark_expected_box,
    BRepPrimAPI_MakeCone as _cadmark_expected_cone,
    BRepPrimAPI_MakeCylinder as _cadmark_expected_cylinder,
    BRepPrimAPI_MakePrism as _cadmark_expected_prism,
    BRepPrimAPI_MakeRevol as _cadmark_expected_revol,
    BRepPrimAPI_MakeSphere as _cadmark_expected_sphere,
    BRepPrimAPI_MakeTorus as _cadmark_expected_torus,
    BRepPrimAPI_MakeWedge as _cadmark_expected_wedge,
)
from OCP.LocOpe import LocOpe_DPrism as _cadmark_expected_taper
from OCP.ShapeUpgrade import (
    ShapeUpgrade_UnifySameDomain as _cadmark_expected_cleanup,
)
from OCP.TopAbs import (
    TopAbs_EDGE as _cadmark_edge,
    TopAbs_FACE as _cadmark_face,
    TopAbs_VERTEX as _cadmark_vertex,
)
from OCP.TopExp import TopExp as _cadmark_top_exp
from OCP.TopTools import TopTools_IndexedMapOfShape as _cadmark_indexed_map
from OCP.TopoDS import TopoDS_Shape as _cadmark_shape_type


class UnsupportedRuntimeVersion(RuntimeError):
    pass


class ProvenanceWrapperError(RuntimeError):
    pass


class UnsupportedProvenanceCapture(RuntimeError):
    pass


# Each entry: module holding the binding, OCP class name, the expected OCP
# base, the semantic operation credited to the user line (None for transport
# that carries existing provenance through unchanged), and the capture
# adapter. Adapters:
#   primitive - every output element is Generated by this operation
#   history   - the builder reports Generated/Modified per input element
#   sweep     - history, with anything left unattributed credited as Generated
#               (profiles from sketches survive into the result with no entry)
#   copy      - transport; partner identity is accepted for located copies
#   cleanup   - transport; distinct merged sources are kept as ambiguity
_cadmark_manifest = (
    ("build123d.topology.three_d", "BRepPrimAPI_MakeBox", _cadmark_expected_box, "Box", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCylinder", _cadmark_expected_cylinder, "Cylinder", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeSphere", _cadmark_expected_sphere, "Sphere", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCone", _cadmark_expected_cone, "Cone", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeTorus", _cadmark_expected_torus, "Torus", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeWedge", _cadmark_expected_wedge, "Wedge", "primitive"),
    ("build123d.topology.utils", "BRepPrimAPI_MakePrism", _cadmark_expected_prism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "LocOpe_DPrism", _cadmark_expected_taper, "Extrude", "primitive"),
    ("build123d.topology.three_d", "BRepFeat_MakeDPrism", _cadmark_expected_dprism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeRevol", _cadmark_expected_revol, "Revolve", "sweep"),
    ("build123d.topology.utils", "BRepOffsetAPI_ThruSections", _cadmark_expected_loft, "Loft", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakePipeShell", _cadmark_expected_pipe, "Sweep", "sweep"),
    ("build123d.topology.three_d", "BRepOffset_MakeOffset", _cadmark_expected_offset, "Thicken", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakeThickSolid", _cadmark_expected_thick, "Shell", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_DraftAngle", _cadmark_expected_draft, "Draft", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Splitter", _cadmark_expected_splitter, "Split", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Fuse", _cadmark_expected_fuse, "BooleanFuse", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Cut", _cadmark_expected_cut, "BooleanCut", "history"),
    ("build123d.topology.three_d", "BRepAlgoAPI_Common", _cadmark_expected_common, "BooleanCommon", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeFillet", _cadmark_expected_fillet, "Fillet", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeChamfer", _cadmark_expected_chamfer, "Chamfer", "history"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Copy", _cadmark_expected_copy, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Transform", _cadmark_expected_transform, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_GTransform", _cadmark_expected_gtransform, None, "copy"),
    ("build123d.topology.shape_core", "ShapeUpgrade_UnifySameDomain", _cadmark_expected_cleanup, None, "cleanup"),
)

# The build123d base classes every stock sketch face and curve object is
# built through. Labelling their construction gives each sketch edge, corner
# and region the user line that drew it; subclasses reach the label through
# their own `super().__init__`, so the whole stock sketch idiom is covered
# without naming each object class.
_cadmark_sketch_bases = (
    ("build123d.objects_sketch", "BaseSketchObject"),
    ("build123d.objects_curve", "BaseLineObject"),
)


# Builder methods that receive input shapes after construction.
_cadmark_input_methods = (
    "SetArguments",
    "SetTools",
    "Add",
    "AddWire",
    "AddVertex",
    "Perform",
    "Initialize",
    "MakeThickSolidByJoin",
)

# Builder methods that return the finished result.
_cadmark_result_methods = ("Shape", "Solid")

_cadmark_kinds = ("face", "edge", "vertex")
_cadmark_kind_enum = {
    "face": _cadmark_face,
    "edge": _cadmark_edge,
    "vertex": _cadmark_vertex,
}
# What a sketch object's own topology is called where the user points at it.
_cadmark_sketch_element_kinds = {
    "face": "region",
    "edge": "curve",
    "vertex": "corner",
}
_cadmark_relation_priority = (
    "Generated",
    "Modified",
    "GeneratedDescendant",
    "ModifiedDescendant",
)


def _cadmark_unique_candidates(candidates):
    seen = set()
    result = []
    for candidate in candidates:
        key = (candidate["operation_id"], candidate["relation"])
        if key not in seen:
            seen.add(key)
            result.append(candidate)
    result.sort(key=lambda item: (item["operation_id"], item["relation"]))
    return result


class _CadmarkShapeTable:
    """Values keyed by shape identity (TShape and location, orientation ignored)."""

    def __init__(self):
        self.index = _cadmark_indexed_map()
        self.values = []

    def slot(self, shape, factory):
        position = self.index.Add(shape)
        if position > len(self.values):
            self.values.append(factory())
        return self.values[position - 1]

    def get(self, shape):
        position = self.index.FindIndex(shape)
        if position == 0:
            return None
        return self.values[position - 1]

    def __len__(self):
        return len(self.values)


class _CadmarkSession:
    def __init__(self, filename):
        self.filename = filename
        self.operations = []
        self.tombstones = []
        # shape -> {"candidates": [...], "allow_partner": bool}
        self.registry = _CadmarkShapeTable()
        self.originals = []
        self.sketch_originals = []
        self.final_maps = {}
        self._next_operation_id = 1
        # Sketch construction, labelled where it happens: one record per
        # stock sketch object, and the shapes it drew keyed by identity.
        self.sketches = []
        self.sketch_registry = _CadmarkShapeTable()
        self.sketch_elements = []
        # Why an element has no sketch route, where an operation was asked
        # and answered nothing. Ancestry always wins over a barrier.
        self.sketch_barriers = _CadmarkShapeTable()
        self._next_sketch_id = 1

    def user_line(self):
        frame = _cadmark_inspect.currentframe()
        try:
            frame = frame.f_back
            while frame is not None:
                if frame.f_code.co_filename == self.filename:
                    return frame.f_lineno
                frame = frame.f_back
        finally:
            del frame
        raise UnsupportedProvenanceCapture(
            f"no user frame for provenance capture in {self.filename}"
        )

    @staticmethod
    def unwrap(value):
        if hasattr(value, "wrapped"):
            value = value.wrapped
        return value

    def collect_shapes(self, value):
        found = []

        def visit(item):
            item = self.unwrap(item)
            if isinstance(item, _cadmark_shape_type):
                found.append(item)
                return
            if isinstance(item, dict):
                for nested in item.values():
                    visit(nested)
                return
            if isinstance(item, (str, bytes)):
                return
            if isinstance(item, (tuple, list, set)):
                for nested in item:
                    visit(nested)
                return
            try:
                for nested in item:
                    visit(nested)
            except (TypeError, RuntimeError):
                return

        visit(value)
        unique = []
        for shape in found:
            if not any(shape.IsSame(existing) for existing in unique):
                unique.append(shape)
        return unique

    @staticmethod
    def make_map(shape, topology_kind):
        result = _cadmark_indexed_map()
        _cadmark_top_exp.MapShapes_s(shape, topology_kind, result)
        return result

    @staticmethod
    def map_values(indexed_map):
        return [indexed_map.FindKey(index) for index in range(1, indexed_map.Extent() + 1)]

    def topology(self, shape):
        return tuple(
            (kind, self.map_values(self.make_map(shape, _cadmark_kind_enum[kind])))
            for kind in _cadmark_kinds
        )

    @staticmethod
    def kind_of(shape):
        shape_type = shape.ShapeType()
        if shape_type == _cadmark_face:
            return "face"
        if shape_type == _cadmark_edge:
            return "edge"
        if shape_type == _cadmark_vertex:
            return "vertex"
        return None

    def inputs_by_kind(self, roots):
        """Every distinct face, edge and vertex of the input shapes."""
        maps = {kind: _cadmark_indexed_map() for kind in _cadmark_kinds}
        for root in roots:
            for kind in _cadmark_kinds:
                _cadmark_top_exp.MapShapes_s(root, _cadmark_kind_enum[kind], maps[kind])
        return {kind: self.map_values(maps[kind]) for kind in _cadmark_kinds}

    def lookup(self, shape, partner_fallback=False):
        record = self.registry.get(shape)
        candidates = list(record["candidates"]) if record else []
        if not candidates and partner_fallback:
            for record in self.registry.values:
                if record["allow_partner"] and shape.IsPartner(record["shape"]):
                    candidates.extend(record["candidates"])
        return _cadmark_unique_candidates(candidates)

    def register(self, shape, candidates, allow_partner=False, replace=False):
        candidates = _cadmark_unique_candidates(candidates)
        if not candidates:
            return
        record = self.registry.slot(
            shape,
            lambda: {"shape": shape, "candidates": [], "allow_partner": False},
        )
        if replace:
            record["candidates"] = candidates
            record["allow_partner"] = allow_partner
        else:
            record["candidates"] = _cadmark_unique_candidates(
                record["candidates"] + candidates
            )
            record["allow_partner"] = record["allow_partner"] or allow_partner

    # ── Sketch lineage ────────────────────────────────────────────────
    #
    # A sketch object's own topology is labelled at construction with the
    # line that drew it. From there a label reaches final topology only
    # where a maker answered: an input the builder directly reports as
    # generating or modifying an output carries its sketch label onto that
    # output. Containment is not a route — an element that merely lies on a
    # face the sketch generated was not drawn by that curve — and neither is
    # position, so where no maker answers, the element gets a barrier
    # naming what was asked, and the consumer states an absence.

    def register_sketch_object(self, instance):
        shape = self.unwrap(instance)
        if shape is None or not isinstance(shape, _cadmark_shape_type) or shape.IsNull():
            return
        topology = self.topology(shape)
        if not any(shapes for _kind, shapes in topology):
            return
        sketch_id = self._next_sketch_id
        self._next_sketch_id += 1
        self.sketches.append(
            {
                "sketch_id": sketch_id,
                "source_line": self.user_line(),
                "object": type(instance).__name__,
            }
        )
        for kind, shapes in topology:
            for member in shapes:
                self.sketch_registry.slot(member, set).add(sketch_id)
                self.sketch_elements.append(
                    {
                        "kind": _cadmark_sketch_element_kinds[kind],
                        "sketch_id": sketch_id,
                    }
                )

    def sketch_lookup(self, shape):
        """Sketch labels on this shape, by identity.

        The exact shape first; failing that, the same underlying shape
        moved or re-oriented, which is how a sketch object reaches its
        plane. Both are construction identity — never proximity or size.
        """
        direct = self.sketch_registry.get(shape)
        if direct:
            return set(direct)
        found = set()
        for position in range(1, self.sketch_registry.index.Extent() + 1):
            candidate = self.sketch_registry.index.FindKey(position)
            if shape.IsPartner(candidate):
                found |= self.sketch_registry.values[position - 1]
        return found

    def register_sketch_ancestry(self, shape, sketch_ids):
        if not sketch_ids:
            return
        self.sketch_registry.slot(shape, set).update(sketch_ids)

    def note_sketch_barrier(self, shape, barrier):
        slot = self.sketch_barriers.slot(shape, lambda: [None])
        slot[0] = barrier

    @staticmethod
    def direct_sources(reached):
        """Input ordinals a maker reported for an output, by input kind.

        Only the relations a maker stated of the shape itself: a
        descendant relation says the output is contained by something the
        input touched, which is not a claim that the input drew it.
        """
        sources = set()
        for relation, input_kind, ordinal in reached:
            if relation in ("Generated", "Modified"):
                sources.add((input_kind, ordinal))
        return sources

    def carry_sketch_lineage(self, result, inputs_by_kind, tables, barrier, identity_tables=None):
        """Move sketch labels from inputs to outputs across one operation."""
        labelled_inputs = {
            (kind, ordinal): labels
            for kind, inputs in inputs_by_kind.items()
            for ordinal, shape in enumerate(inputs)
            for labels in (self.sketch_lookup(shape),)
            if labels
        }
        if not labelled_inputs:
            return
        for kind, outputs in self.topology(result):
            for output in outputs:
                if self.sketch_lookup(output):
                    continue
                sketch_ids = set()
                for source in self.direct_sources(tables[kind].get(output) or ()):
                    sketch_ids |= labelled_inputs.get(source, set())
                if identity_tables is not None:
                    same = identity_tables[kind].get(output)
                    if same is not None:
                        sketch_ids |= labelled_inputs.get((kind, same), set())
                if sketch_ids:
                    self.register_sketch_ancestry(output, sketch_ids)
                elif barrier is not None:
                    self.note_sketch_barrier(output, barrier)

    def sketch_state(self, shape):
        sketch_ids = self.sketch_lookup(shape)
        if sketch_ids:
            return {"candidates": sorted(sketch_ids)}
        barrier = self.sketch_barriers.get(shape)
        if barrier is not None and barrier[0] is not None:
            return {"barrier": barrier[0]}
        return {}

    def new_operation(self, source_line, operation, api_class):
        operation_id = self._next_operation_id
        self._next_operation_id += 1
        self.operations.append(
            {
                "operation_id": operation_id,
                "source_line": source_line,
                "operation": operation,
                "api_class": api_class,
            }
        )
        return operation_id

    @staticmethod
    def history_results(builder, method, shape):
        try:
            result = getattr(builder, method)(shape)
            return list(result)
        except (AttributeError, TypeError, RuntimeError):
            try:
                history = builder.History()
                result = getattr(history, method)(shape)
                return list(result)
            except (AttributeError, TypeError, RuntimeError):
                return []

    def history_table(self, builder, inputs_by_kind):
        """Index every shape the builder reports as changed, once per input.

        Returns one table per output kind. Each entry maps an output shape to
        the set of (relation, input kind, input ordinal) triples that reach
        it: a direct relation when the builder named the shape itself, a
        descendant relation when it named a shape containing it.
        """
        tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}

        def note(shape, kind, relation, input_kind, ordinal):
            tables[kind].slot(shape, set).add((relation, input_kind, ordinal))

        for input_kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                for relation in ("Generated", "Modified"):
                    for changed in self.history_results(builder, relation, input_shape):
                        changed_kind = self.kind_of(changed)
                        if changed_kind is not None:
                            note(changed, changed_kind, relation, input_kind, ordinal)
                        for kind, members in self.topology(changed):
                            for member in members:
                                if changed_kind == kind and member.IsSame(changed):
                                    continue
                                note(
                                    member,
                                    kind,
                                    relation + "Descendant",
                                    input_kind,
                                    ordinal,
                                )
        return tables

    @staticmethod
    def select_relation(relations):
        for relation in _cadmark_relation_priority:
            if relation in relations:
                return relation
        return None

    def capture_primitive(self, builder, result, operation, api_class):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, shapes in self.topology(result):
            for shape in shapes:
                self.register(
                    shape, [candidate], allow_partner=True, replace=True
                )

    def capture_history(self, builder, result, operation, api_class):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)

        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                try:
                    deleted = bool(builder.IsDeleted(input_shape))
                except (AttributeError, TypeError, RuntimeError):
                    deleted = False
                if deleted:
                    self.tombstones.append(
                        {
                            "operation_id": operation_id,
                            "kind": kind,
                            "ordinal": ordinal,
                        }
                    )

        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            for output in outputs:
                reached = tables[kind].get(output) or set()
                # Prefer history reported against inputs of the output's own
                # kind; fall back to what any input reports.
                same_kind = {
                    relation
                    for relation, input_kind, _ordinal in reached
                    if input_kind == kind
                }
                relations = same_kind or {relation for relation, _k, _o in reached}
                selected = self.select_relation(relations)
                if selected is not None:
                    self.register(
                        output,
                        [{"operation_id": operation_id, "relation": selected}],
                        replace=True,
                    )

        self.carry_sketch_lineage(
            result,
            inputs_by_kind,
            tables,
            {"reason": "history_empty", "operation_id": operation_id},
        )
        return operation_id

    def capture_sweep(self, builder, result, operation, api_class):
        # A sweep (prism, revolve, loft, pipe, offset) reports the topology it
        # generates from each profile element, but the profile itself survives
        # as the base of the result with no history entry. The profile usually
        # comes from a sketch, which is outside the instrumented set, so any
        # output the history left unattributed is credited to the sweep as
        # Generated.
        operation_id = self.capture_history(builder, result, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, outputs in self.topology(result):
            for output in outputs:
                if not self.lookup(output):
                    self.register(output, [candidate])

    def capture_transport(self, builder, result, allow_partner, barrier=None):
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)
        input_tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}
        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                input_tables[kind].slot(input_shape, lambda ordinal=ordinal: ordinal)
        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            inputs = inputs_by_kind[kind]
            for output in outputs:
                sources = set()
                same = input_tables[kind].get(output)
                if same is not None:
                    sources.add(same)
                for _relation, input_kind, ordinal in tables[kind].get(output) or ():
                    if input_kind == kind:
                        sources.add(ordinal)
                candidates = []
                for ordinal in sorted(sources):
                    candidates.extend(self.lookup(inputs[ordinal]))
                if not candidates:
                    candidates.extend(self.lookup(output))
                self.register(output, candidates, allow_partner=allow_partner)

        # Transport keeps a sketch label only where the same shape came
        # through. A merged output is a new shape whose maker answers
        # nothing, and the clean-up step is the measured case of that.
        self.carry_sketch_lineage(
            result,
            inputs_by_kind,
            tables,
            barrier,
            identity_tables=input_tables,
        )

    def capture(self, builder, result, operation, adapter, api_class):
        result = self.unwrap(result)
        if result.IsNull():
            return
        if adapter == "primitive":
            self.capture_primitive(builder, result, operation, api_class)
        elif adapter == "history":
            self.capture_history(builder, result, operation, api_class)
        elif adapter == "sweep":
            self.capture_sweep(builder, result, operation, api_class)
        elif adapter == "copy":
            self.capture_transport(builder, result, allow_partner=True)
        elif adapter == "cleanup":
            self.capture_transport(
                builder,
                result,
                allow_partner=False,
                barrier={"reason": "clean_up"},
            )

    def wrap(self, original, operation, adapter, api_class):
        session = self

        def init(instance, *args, **kwargs):
            instance._cadmark_source_line = session.user_line()
            instance._cadmark_inputs = session.collect_shapes((args, kwargs))
            instance._cadmark_captured = False
            original.__init__(instance, *args, **kwargs)

        namespace = {"__init__": init, "__module__": original.__module__}

        # Builders hand back their result through Shape() or, for some
        # primitives, Solid(); whichever is called first captures it.
        for accessor_name in _cadmark_result_methods:
            if not hasattr(original, accessor_name):
                continue
            original_accessor = getattr(original, accessor_name)

            def accessor(instance, *args, _accessor=original_accessor, **kwargs):
                result = _accessor(instance, *args, **kwargs)
                if not instance._cadmark_captured:
                    instance._cadmark_captured = True
                    session.capture(instance, result, operation, adapter, api_class)
                return result

            namespace[accessor_name] = accessor

        for method_name in _cadmark_input_methods:
            if not hasattr(original, method_name):
                continue
            original_method = getattr(original, method_name)

            def capture_input(instance, *args, _method=original_method, **kwargs):
                for captured in session.collect_shapes((args, kwargs)):
                    if not any(
                        captured.IsSame(existing)
                        for existing in instance._cadmark_inputs
                    ):
                        instance._cadmark_inputs.append(captured)
                return _method(instance, *args, **kwargs)

            namespace[method_name] = capture_input

        return type(api_class, (original,), namespace)

    def wrap_sketch_base(self, original_init):
        session = self

        def init(instance, *args, **kwargs):
            original_init(instance, *args, **kwargs)
            session.register_sketch_object(instance)

        return init

    def install_sketch_labelling(self, bases=None):
        bases = _cadmark_sketch_bases if bases is None else bases
        installed = []
        try:
            for module_name, attribute in bases:
                module = _cadmark_importlib.import_module(module_name)
                base = getattr(module, attribute)
                original_init = base.__init__
                base.__init__ = self.wrap_sketch_base(original_init)
                if base.__init__ is original_init:
                    raise ProvenanceWrapperError(
                        f"failed to label {module_name}.{attribute}"
                    )
                installed.append((base, original_init))
            self.sketch_originals = installed
        except Exception:
            for base, original_init in reversed(installed):
                base.__init__ = original_init
            raise

    def restore_sketch_labelling(self):
        failures = []
        for base, original_init in reversed(self.sketch_originals):
            try:
                base.__init__ = original_init
            except Exception:
                failures.append(base.__name__)
        self.sketch_originals = []
        return failures

    def install(self, manifest=None):
        manifest = _cadmark_manifest if manifest is None else manifest
        installed = []
        try:
            for module_name, attribute, expected, operation, adapter in manifest:
                module = _cadmark_importlib.import_module(module_name)
                original = getattr(module, attribute)
                if not isinstance(original, type) or not issubclass(original, expected):
                    raise ProvenanceWrapperError(
                        f"{module_name}.{attribute} is not the expected OCP base"
                    )
                wrapped = self.wrap(original, operation, adapter, attribute)
                setattr(module, attribute, wrapped)
                if getattr(module, attribute) is not wrapped:
                    raise ProvenanceWrapperError(
                        f"failed to replace {module_name}.{attribute}"
                    )
                installed.append((module, attribute, original))
            self.install_sketch_labelling()
            self.originals = installed
        except Exception:
            for module, attribute, original in reversed(installed):
                setattr(module, attribute, original)
            raise

    def restore(self):
        failures = self.restore_sketch_labelling()
        for module, attribute, original in reversed(self.originals):
            try:
                setattr(module, attribute, original)
                if getattr(module, attribute) is not original:
                    failures.append(f"{module.__name__}.{attribute}")
            except Exception:
                failures.append(f"{module.__name__}.{attribute}")
        self.originals = []
        if failures:
            raise ProvenanceWrapperError(
                "failed to restore " + ", ".join(failures)
            )

    def finalise(self, shape):
        shape = self.unwrap(shape)
        self.final_maps = {
            kind: self.make_map(shape, _cadmark_kind_enum[kind])
            for kind in _cadmark_kinds
        }
        result = {
            "schema_version": 1,
            "operations": list(self.operations),
            "faces": [],
            "edges": [],
            "vertices": [],
            "tombstones": list(self.tombstones),
            "sketches": list(self.sketches),
            "sketch_elements": list(self.sketch_elements),
        }
        for kind, output_name in (
            ("face", "faces"),
            ("edge", "edges"),
            ("vertex", "vertices"),
        ):
            for final_shape in self.map_values(self.final_maps[kind]):
                result[output_name].append(
                    {
                        "candidates": self.lookup(
                            final_shape, partner_fallback=True
                        ),
                        "sketch": self.sketch_state(final_shape),
                    }
                )
        return result

    def topology_index(self, shape, kind):
        indexed = self.final_maps[kind]
        index = indexed.FindIndex(shape)
        if index == 0:
            raise UnsupportedProvenanceCapture(
                f"{kind} is absent from the final topology map"
            )
        return index - 1


def _cadmark_validate_runtime(actual=None):
    if actual is None:
        actual = (
            _cadmark_sys.version_info[:2],
            _cadmark_build123d.__version__,
            _cadmark_ocp.__version__,
            _cadmark_metadata.version("cadquery-ocp-novtk"),
        )
    expected = ((3, 12), "0.11.1", "7.9.3.1", "7.9.3.1.1")
    if actual != expected:
        raise UnsupportedRuntimeVersion(
            f"expected Python/build123d/OCP/distribution {expected}, got {actual}"
        )


def _cadmark_install(filename, manifest=None, actual_runtime=None):
    _cadmark_validate_runtime(actual_runtime)
    session = _CadmarkSession(filename)
    session.install(manifest)
    return session
