import importlib as _cadmark_importlib
import importlib.metadata as _cadmark_metadata
import inspect as _cadmark_inspect
import sys as _cadmark_sys

import OCP as _cadmark_ocp
import build123d as _cadmark_build123d
from OCP.BRepAlgoAPI import (
    BRepAlgoAPI_Common as _cadmark_expected_common,
    BRepAlgoAPI_Cut as _cadmark_expected_cut,
    BRepAlgoAPI_Fuse as _cadmark_expected_fuse,
    BRepAlgoAPI_Splitter as _cadmark_expected_splitter,
)
from OCP.BRepBuilderAPI import (
    BRepBuilderAPI_Copy as _cadmark_expected_copy,
    BRepBuilderAPI_GTransform as _cadmark_expected_gtransform,
    BRepBuilderAPI_Transform as _cadmark_expected_transform,
)
from OCP.BRepFeat import BRepFeat_MakeDPrism as _cadmark_expected_dprism
from OCP.BRepFilletAPI import (
    BRepFilletAPI_MakeChamfer as _cadmark_expected_chamfer,
    BRepFilletAPI_MakeFillet as _cadmark_expected_fillet,
    BRepFilletAPI_MakeFillet2d as _cadmark_expected_fillet2d,
)
from OCP.BRepOffset import BRepOffset_MakeOffset as _cadmark_expected_offset
from OCP.BRepOffsetAPI import (
    BRepOffsetAPI_DraftAngle as _cadmark_expected_draft,
    BRepOffsetAPI_MakeOffset as _cadmark_expected_offset2d,
    BRepOffsetAPI_MakePipeShell as _cadmark_expected_pipe,
    BRepOffsetAPI_MakeThickSolid as _cadmark_expected_thick,
    BRepOffsetAPI_ThruSections as _cadmark_expected_loft,
)
from OCP.BRepPrimAPI import (
    BRepPrimAPI_MakeBox as _cadmark_expected_box,
    BRepPrimAPI_MakeCone as _cadmark_expected_cone,
    BRepPrimAPI_MakeCylinder as _cadmark_expected_cylinder,
    BRepPrimAPI_MakePrism as _cadmark_expected_prism,
    BRepPrimAPI_MakeRevol as _cadmark_expected_revol,
    BRepPrimAPI_MakeSphere as _cadmark_expected_sphere,
    BRepPrimAPI_MakeTorus as _cadmark_expected_torus,
    BRepPrimAPI_MakeWedge as _cadmark_expected_wedge,
)
from OCP.LocOpe import LocOpe_DPrism as _cadmark_expected_taper
from OCP.ShapeUpgrade import (
    ShapeUpgrade_UnifySameDomain as _cadmark_expected_cleanup,
)
from OCP.TopAbs import (
    TopAbs_EDGE as _cadmark_edge,
    TopAbs_FACE as _cadmark_face,
    TopAbs_VERTEX as _cadmark_vertex,
)
from OCP.TopExp import TopExp as _cadmark_top_exp
from OCP.TopLoc import TopLoc_Location as _cadmark_location_type
from OCP.TopTools import (
    TopTools_IndexedMapOfShape as _cadmark_indexed_map,
    TopTools_ListOfShape as _cadmark_shape_list,
)
from OCP.TopoDS import TopoDS_Shape as _cadmark_shape_type
from OCP.Standard import Standard_TypeMismatch as _cadmark_ocp_type_mismatch


class UnsupportedRuntimeVersion(RuntimeError):
    pass


class ProvenanceWrapperError(RuntimeError):
    pass


class UnsupportedProvenanceCapture(RuntimeError):
    pass


# Each entry: module holding the binding, OCP class name, the expected OCP
# base, the semantic operation credited to the user line (None for transport
# that carries existing provenance through unchanged), and the capture
# adapter. Adapters:
#   primitive - every output element is Generated by this operation
#   history   - the builder reports Generated/Modified per input element
#   sweep     - history, with anything left unattributed credited as Generated
#               (profiles from sketches survive into the result with no entry)
#   copy      - transport; partner identity is accepted for located copies
#   cleanup   - transport; distinct merged sources are kept as ambiguity
_cadmark_manifest = (
    ("build123d.topology.three_d", "BRepPrimAPI_MakeBox", _cadmark_expected_box, "Box", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCylinder", _cadmark_expected_cylinder, "Cylinder", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeSphere", _cadmark_expected_sphere, "Sphere", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCone", _cadmark_expected_cone, "Cone", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeTorus", _cadmark_expected_torus, "Torus", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeWedge", _cadmark_expected_wedge, "Wedge", "primitive"),
    ("build123d.topology.utils", "BRepPrimAPI_MakePrism", _cadmark_expected_prism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "LocOpe_DPrism", _cadmark_expected_taper, "Extrude", "primitive"),
    ("build123d.topology.three_d", "BRepFeat_MakeDPrism", _cadmark_expected_dprism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeRevol", _cadmark_expected_revol, "Revolve", "sweep"),
    ("build123d.topology.utils", "BRepOffsetAPI_ThruSections", _cadmark_expected_loft, "Loft", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakePipeShell", _cadmark_expected_pipe, "Sweep", "sweep"),
    ("build123d.topology.three_d", "BRepOffset_MakeOffset", _cadmark_expected_offset, "Thicken", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakeThickSolid", _cadmark_expected_thick, "Shell", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_DraftAngle", _cadmark_expected_draft, "Draft", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Splitter", _cadmark_expected_splitter, "Split", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Fuse", _cadmark_expected_fuse, "BooleanFuse", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Cut", _cadmark_expected_cut, "BooleanCut", "history"),
    ("build123d.topology.three_d", "BRepAlgoAPI_Common", _cadmark_expected_common, "BooleanCommon", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeFillet", _cadmark_expected_fillet, "Fillet", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeChamfer", _cadmark_expected_chamfer, "Chamfer", "history"),
    # The 2D chamfer of a sketch face or wire, and the 2D offset of a wire:
    # both report per-edge history, so a chamfered or offset profile keeps
    # the line that drew each surviving curve.
    ("build123d.topology.two_d", "BRepFilletAPI_MakeFillet2d", _cadmark_expected_fillet2d, "Chamfer", "history"),
    ("build123d.topology.one_d", "BRepFilletAPI_MakeFillet2d", _cadmark_expected_fillet2d, "Chamfer", "history"),
    ("build123d.topology.one_d", "BRepOffsetAPI_MakeOffset", _cadmark_expected_offset2d, "Offset", "history"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Copy", _cadmark_expected_copy, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Transform", _cadmark_expected_transform, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_GTransform", _cadmark_expected_gtransform, None, "copy"),
    ("build123d.topology.shape_core", "ShapeUpgrade_UnifySameDomain", _cadmark_expected_cleanup, None, "cleanup"),
)

# The build123d base classes every stock sketch face and curve object is
# built through. Labelling their construction gives each sketch edge, corner
# and region the user line that drew it; subclasses reach the label through
# their own `super().__init__`, so the whole stock sketch idiom is covered
# without naming each object class.
_cadmark_sketch_bases = (
    ("build123d.objects_sketch", "BaseSketchObject"),
    ("build123d.objects_curve", "BaseLineObject"),
)


# Builder methods that receive input shapes after construction.
_cadmark_input_methods = (
    "SetArguments",
    "SetTools",
    "Add",
    "AddWire",
    "AddVertex",
    "Perform",
    "Initialize",
    "MakeThickSolidByJoin",
)

# Builder methods that return the finished result.
_cadmark_result_methods = ("Shape", "Solid")

_cadmark_kinds = ("face", "edge", "vertex")
_cadmark_kind_enum = {
    "face": _cadmark_face,
    "edge": _cadmark_edge,
    "vertex": _cadmark_vertex,
}
_cadmark_relation_priority = (
    "Generated",
    "Modified",
    "GeneratedDescendant",
    "ModifiedDescendant",
)


def _cadmark_unique_candidates(candidates):
    seen = set()
    result = []
    for candidate in candidates:
        key = (candidate["operation_id"], candidate["relation"])
        if key not in seen:
            seen.add(key)
            result.append(candidate)
    result.sort(key=lambda item: (item["operation_id"], item["relation"]))
    return result


# Stripping a shape's location leaves its underlying shape alone, so two
# shapes are partners (`IsPartner`) exactly when their location-stripped
# forms are the same key in an indexed map.
_cadmark_no_location = _cadmark_location_type()


def _cadmark_partner_key(shape):
    return shape.Located(_cadmark_no_location)


class _CadmarkShapeTable:
    """Values keyed by shape identity (TShape and location, orientation ignored).

    A second index groups the entries by partner identity — the same
    underlying shape at any location — so a partner lookup is a hash probe
    rather than a scan of every entry.
    """

    def __init__(self):
        self.index = _cadmark_indexed_map()
        self.values = []
        self.partners = _cadmark_indexed_map()
        # One list per partner key: the positions of its entries, in
        # insertion order.
        self.partner_positions = []

    def slot(self, shape, factory):
        position = self.index.Add(shape)
        if position > len(self.values):
            self.values.append(factory())
            partner = self.partners.Add(_cadmark_partner_key(shape))
            if partner > len(self.partner_positions):
                self.partner_positions.append([])
            self.partner_positions[partner - 1].append(position)
        return self.values[position - 1]

    def get(self, shape):
        position = self.index.FindIndex(shape)
        if position == 0:
            return None
        return self.values[position - 1]

    def partner_values(self, shape):
        """The values of every entry sharing this shape's underlying shape,
        the exact entry included, in insertion order."""
        partner = self.partners.FindIndex(_cadmark_partner_key(shape))
        if partner == 0:
            return []
        return [self.values[position - 1] for position in self.partner_positions[partner - 1]]

    def __len__(self):
        return len(self.values)


class _CadmarkSession:
    def __init__(self, filename):
        self.filename = filename
        self.operations = []
        self.tombstones = []
        # shape -> {"candidates": [...], "allow_partner": bool}
        self.registry = _CadmarkShapeTable()
        # Located default-rotate results share a TShape with their retained
        # receiver, so only an explicit subsequent move may carry their
        # provenance to a new placement.
        self.location_only_transforms = _CadmarkShapeTable()
        self.originals = []
        self.sketch_originals = []
        self.final_maps = {}
        self._next_operation_id = 1
        self.semantic_stack = []
        # Sketch construction, labelled where it happens: one record per
        # stock sketch object, and the shapes it drew keyed by identity.
        self.sketches = []
        self.sketch_registry = _CadmarkShapeTable()
        # Why an element has no sketch route, where an operation was asked
        # and answered nothing. Ancestry always wins over a barrier.
        self.sketch_barriers = _CadmarkShapeTable()
        self._next_sketch_id = 1

    def user_line(self):
        frame = _cadmark_inspect.currentframe()
        try:
            frame = frame.f_back
            while frame is not None:
                if frame.f_code.co_filename == self.filename:
                    return frame.f_lineno
                frame = frame.f_back
        finally:
            del frame
        raise UnsupportedProvenanceCapture(
            f"no user frame for provenance capture in {self.filename}"
        )

    @staticmethod
    def unwrap(value):
        if hasattr(value, "wrapped"):
            value = value.wrapped
        return value

    def collect_shapes(self, value):
        found = []

        def visit(item):
            item = self.unwrap(item)
            if isinstance(item, _cadmark_shape_type):
                found.append(item)
                return
            if isinstance(item, dict):
                for nested in item.values():
                    visit(nested)
                return
            if isinstance(item, (str, bytes)):
                return
            if isinstance(item, (tuple, list, set)):
                for nested in item:
                    visit(nested)
                return
            try:
                for nested in item:
                    visit(nested)
            except (TypeError, RuntimeError):
                return

        visit(value)
        unique = []
        for shape in found:
            if not any(shape.IsSame(existing) for existing in unique):
                unique.append(shape)
        return unique

    @staticmethod
    def make_map(shape, topology_kind):
        result = _cadmark_indexed_map()
        _cadmark_top_exp.MapShapes_s(shape, topology_kind, result)
        return result

    @staticmethod
    def map_values(indexed_map):
        return [indexed_map.FindKey(index) for index in range(1, indexed_map.Extent() + 1)]

    def topology(self, shape):
        return tuple(
            (kind, self.map_values(self.make_map(shape, _cadmark_kind_enum[kind])))
            for kind in _cadmark_kinds
        )

    @staticmethod
    def kind_of(shape):
        shape_type = shape.ShapeType()
        if shape_type == _cadmark_face:
            return "face"
        if shape_type == _cadmark_edge:
            return "edge"
        if shape_type == _cadmark_vertex:
            return "vertex"
        return None

    def inputs_by_kind(self, roots):
        """Every distinct face, edge and vertex of the input shapes."""
        maps = {kind: _cadmark_indexed_map() for kind in _cadmark_kinds}
        for root in roots:
            for kind in _cadmark_kinds:
                _cadmark_top_exp.MapShapes_s(root, _cadmark_kind_enum[kind], maps[kind])
        return {kind: self.map_values(maps[kind]) for kind in _cadmark_kinds}

    def lookup(self, shape, partner_fallback=False):
        record = self.registry.get(shape)
        candidates = list(record["candidates"]) if record else []
        if not candidates and partner_fallback:
            for record in self.registry.partner_values(shape):
                if record["allow_partner"]:
                    candidates.extend(record["candidates"])
        return _cadmark_unique_candidates(candidates)

    def register(self, shape, candidates, allow_partner=False, replace=False):
        candidates = _cadmark_unique_candidates(candidates)
        if not candidates:
            return
        record = self.registry.slot(
            shape,
            lambda: {"shape": shape, "candidates": [], "allow_partner": False},
        )
        if replace:
            record["candidates"] = candidates
            record["allow_partner"] = allow_partner
        else:
            record["candidates"] = _cadmark_unique_candidates(
                record["candidates"] + candidates
            )
            record["allow_partner"] = record["allow_partner"] or allow_partner

    # ── Sketch lineage ────────────────────────────────────────────────
    #
    # A sketch object's own topology is labelled at construction with the
    # line that drew it. From there a label reaches final topology only
    # where a maker answered: an input the builder directly reports as
    # generating or modifying an output carries its sketch label onto that
    # output. Containment is not a route — an element that merely lies on a
    # face the sketch generated was not drawn by that curve — and neither is
    # position, so where no maker answers, the element gets a barrier
    # naming what was asked, and the consumer states an absence.

    def begin_sketch_object(self, instance, arguments):
        """Label what a sketch object is about to draw, before it draws.

        A stock sketch object hands its geometry to the enclosing builder
        — where a subtract or fuse consumes it — before its own base class
        finishes constructing, so the label must be on the input shapes
        by then for the boolean's history to carry it. The record is
        opened here and the finished object's own topology is labelled
        under the same identity once construction completes.
        """
        sketch_id = self._next_sketch_id
        self._next_sketch_id += 1
        self.sketches.append(
            {
                "sketch_id": sketch_id,
                "source_line": self.user_line(),
                "object": type(instance).__name__,
            }
        )
        for shape in self.collect_shapes(arguments):
            self.label_sketch_topology(shape, sketch_id)
        return sketch_id

    def register_sketch_object(self, instance, sketch_id):
        shape = self.unwrap(instance)
        if shape is None or not isinstance(shape, _cadmark_shape_type) or shape.IsNull():
            return
        self.label_sketch_topology(shape, sketch_id)

    def label_sketch_topology(self, shape, sketch_id):
        for _kind, shapes in self.topology(shape):
            for member in shapes:
                self.sketch_registry.slot(member, set).add(sketch_id)

    def sketch_lookup(self, shape):
        """Sketch labels on this shape, by identity.

        The exact shape first; failing that, the same underlying shape
        moved or re-oriented, which is how a sketch object reaches its
        plane. Both are construction identity — never proximity or size.
        """
        direct = self.sketch_registry.get(shape)
        if direct:
            return set(direct)
        found = set()
        for labels in self.sketch_registry.partner_values(shape):
            found |= labels
        return found

    def register_sketch_ancestry(self, shape, sketch_ids):
        if not sketch_ids:
            return
        self.sketch_registry.slot(shape, set).update(sketch_ids)

    def note_sketch_barrier(self, shape, barrier):
        slot = self.sketch_barriers.slot(shape, lambda: [None])
        slot[0] = barrier

    def barrier_lookup(self, shape):
        """The barrier on this shape, by the same identity labels use.

        The exact shape first; failing that, the same underlying shape
        moved or re-oriented, which is how a sketch reaches its plane.
        """
        direct = self.sketch_barriers.get(shape)
        if direct and direct[0] is not None:
            return direct[0]
        for existing in self.sketch_barriers.partner_values(shape):
            if existing[0] is not None:
                return existing[0]
        return None

    @staticmethod
    def direct_sources(reached):
        """Input ordinals a maker reported for an output, by input kind.

        Only the relations a maker stated of the shape itself: a
        descendant relation says the output is contained by something the
        input touched, which is not a claim that the input drew it.
        """
        sources = set()
        for relation, input_kind, ordinal in reached:
            if relation in ("Generated", "Modified"):
                sources.add((input_kind, ordinal))
        return sources

    def carry_sketch_lineage(
        self, result, inputs_by_kind, tables, barrier, identity_tables=None, strict=False
    ):
        """Move sketch labels from inputs to outputs across one operation.

        Under `strict` — which is how a barrier step such as build123d's
        clean-up runs — only exact shape identity carries a label, so a
        label reaches an output solely when that output is the very shape
        the step left alone. Elsewhere the looser partner identity moves a
        label onto the same underlying shape relocated to its plane.
        """
        label_of = self.sketch_registry.get if strict else self.sketch_lookup
        labelled_inputs = {
            (kind, ordinal): set(labels)
            for kind, inputs in inputs_by_kind.items()
            for ordinal, shape in enumerate(inputs)
            for labels in (label_of(shape) or (),)
            if labels
        }
        # An input that already lost its route carries the barrier that
        # lost it: the step that first broke the route is the honest
        # answer, not the last step to pass the shape on.
        barriered_inputs = {
            (kind, ordinal): existing
            for kind, inputs in inputs_by_kind.items()
            for ordinal, shape in enumerate(inputs)
            for existing in (self.barrier_lookup(shape),)
            if existing is not None
        }
        if not labelled_inputs and not barriered_inputs:
            return
        for kind, outputs in self.topology(result):
            for output in outputs:
                if label_of(output):
                    continue
                sources = self.direct_sources(tables[kind].get(output) or ())
                if identity_tables is not None:
                    same = identity_tables[kind].get(output)
                    if same is not None:
                        sources.add((kind, same))
                sketch_ids = set()
                for source in sources:
                    sketch_ids |= labelled_inputs.get(source, set())
                if sketch_ids:
                    self.register_sketch_ancestry(output, sketch_ids)
                    continue
                # A shape that already carries a barrier keeps it: the step
                # that first lost the route is the honest answer.
                if self.barrier_lookup(output) is not None:
                    continue
                inherited = [
                    barriered_inputs[source]
                    for source in sorted(sources)
                    if source in barriered_inputs
                ]
                if inherited:
                    self.note_sketch_barrier(output, inherited[0])
                elif barrier is not None and (labelled_inputs or sources):
                    self.note_sketch_barrier(output, barrier)

    def sketch_state(self, shape):
        sketch_ids = self.sketch_lookup(shape)
        if sketch_ids:
            return {"candidates": sorted(sketch_ids)}
        barrier = self.barrier_lookup(shape)
        if barrier is not None:
            return {"barrier": barrier}
        return {}

    def new_operation(self, source_line, operation, api_class):
        operation_id = self._next_operation_id
        self._next_operation_id += 1
        self.operations.append(
            {
                "operation_id": operation_id,
                "source_line": source_line,
                "operation": operation,
                "api_class": api_class,
            }
        )
        return operation_id

    def push_semantic(self, source_line, operation, api_class):
        self.semantic_stack.append((source_line, operation, api_class))

    def pop_semantic(self):
        self.semantic_stack.pop()

    def active_semantic(self):
        if self.semantic_stack:
            return self.semantic_stack[-1]
        return None

    @staticmethod
    def shape_list(shapes):
        """An OCCT shape list as a Python list.

        Iterating the binding's list ends every pass with a C++ exception
        whose unwinding costs more than the maker query itself; draining a
        copy through First/RemoveFirst never raises. The maker's own list
        is left untouched.
        """
        if not isinstance(shapes, _cadmark_shape_list):
            return list(shapes)
        size = shapes.Size()
        if size == 0:
            return []
        if size == 1:
            return [shapes.First()]
        drained = _cadmark_shape_list()
        drained.Assign(shapes)
        result = []
        while not drained.IsEmpty():
            result.append(drained.First())
            drained.RemoveFirst()
        return result

    @classmethod
    def history_results(cls, builder, method, shape):
        # A maker that answers only for one kind of input (the 2D fillet
        # builder speaks of edges alone) raises an OCCT type mismatch for
        # the others; that is "no history for this input", not a fault.
        try:
            result = getattr(builder, method)(shape)
            return cls.shape_list(result)
        except (AttributeError, TypeError, RuntimeError, _cadmark_ocp_type_mismatch):
            try:
                history = builder.History()
                result = getattr(history, method)(shape)
                return cls.shape_list(result)
            except (AttributeError, TypeError, RuntimeError, _cadmark_ocp_type_mismatch):
                return []

    def history_table(self, builder, inputs_by_kind):
        """Index every shape the builder reports as changed, once per input.

        Returns one table per output kind. Each entry maps an output shape to
        the set of (relation, input kind, input ordinal) triples that reach
        it: a direct relation when the builder named the shape itself, a
        descendant relation when it named a shape containing it.
        """
        tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}

        def note(shape, kind, relation, input_kind, ordinal):
            tables[kind].slot(shape, set).add((relation, input_kind, ordinal))

        for input_kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                for relation in ("Generated", "Modified"):
                    for changed in self.history_results(builder, relation, input_shape):
                        changed_kind = self.kind_of(changed)
                        if changed_kind is not None:
                            note(changed, changed_kind, relation, input_kind, ordinal)
                        for kind, members in self.topology(changed):
                            for member in members:
                                if changed_kind == kind and member.IsSame(changed):
                                    continue
                                note(
                                    member,
                                    kind,
                                    relation + "Descendant",
                                    input_kind,
                                    ordinal,
                                )
        return tables

    @staticmethod
    def select_relation(relations):
        for relation in _cadmark_relation_priority:
            if relation in relations:
                return relation
        return None

    def capture_primitive(self, builder, result, operation, api_class):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, shapes in self.topology(result):
            for shape in shapes:
                self.register(
                    shape, [candidate], allow_partner=True, replace=True
                )

    def capture_location_only_transform(self, result, source_line, operation, api_class):
        operation_id = self.new_operation(source_line, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Modified"}
        for _kind, shapes in self.topology(self.unwrap(result)):
            for shape in shapes:
                self.location_only_transforms.slot(shape, lambda: True)
                self.register(shape, [candidate])

    def has_location_only_transform(self, shape):
        return any(
            self.location_only_transforms.get(member) is not None
            for _kind, members in self.topology(self.unwrap(shape))
            for member in members
        )

    def capture_location_transport(self, original, result):
        """Carry a located default-rotate result to one later placement.

        This is deliberately exact-location transport rather than partner
        fallback: the retained receiver has the same partner topology but was
        not rotated.
        """
        inputs_by_kind = dict(self.topology(self.unwrap(original)))
        for kind, outputs in self.topology(self.unwrap(result)):
            for output in outputs:
                candidates = []
                for input_shape in inputs_by_kind[kind]:
                    if output.IsPartner(input_shape):
                        candidates.extend(self.lookup(input_shape))
                self.register(output, candidates, replace=True)

    def capture_active_semantic_relation(self, result, source_line, operation, api_class):
        operation_id = self.new_operation(source_line, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Modified"}
        for _kind, shapes in self.topology(result):
            for shape in shapes:
                self.register(shape, [candidate], allow_partner=True, replace=True)

    def capture_history(self, builder, result, operation, api_class, allow_partner=False):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)

        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                try:
                    deleted = bool(builder.IsDeleted(input_shape))
                except (AttributeError, TypeError, RuntimeError):
                    deleted = False
                if deleted:
                    self.tombstones.append(
                        {
                            "operation_id": operation_id,
                            "kind": kind,
                            "ordinal": ordinal,
                        }
                    )

        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            for output in outputs:
                reached = tables[kind].get(output) or set()
                # Prefer history reported against inputs of the output's own
                # kind; fall back to what any input reports.
                same_kind = {
                    relation
                    for relation, input_kind, _ordinal in reached
                    if input_kind == kind
                }
                relations = same_kind or {relation for relation, _k, _o in reached}
                selected = self.select_relation(relations)
                if selected is not None:
                    self.register(
                        output,
                        [{"operation_id": operation_id, "relation": selected}],
                        allow_partner=allow_partner,
                        replace=True,
                    )

        self.carry_sketch_lineage(
            result,
            inputs_by_kind,
            tables,
            {"reason": "history_empty", "operation_id": operation_id},
        )
        return operation_id

    def capture_sweep(self, builder, result, operation, api_class):
        # A sweep (prism, revolve, loft, pipe, offset) reports the topology it
        # generates from each profile element, but the profile itself survives
        # as the base of the result with no history entry. The profile usually
        # comes from a sketch, which is outside the instrumented set, so any
        # output the history left unattributed is credited to the sweep as
        # Generated.
        operation_id = self.capture_history(builder, result, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, outputs in self.topology(result):
            for output in outputs:
                if not self.lookup(output):
                    self.register(output, [candidate])

    def capture_transport(self, builder, result, allow_partner, barrier=None):
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)
        input_tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}
        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                input_tables[kind].slot(input_shape, lambda ordinal=ordinal: ordinal)
        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            inputs = inputs_by_kind[kind]
            for output in outputs:
                sources = set()
                same = input_tables[kind].get(output)
                if same is not None:
                    sources.add(same)
                for _relation, input_kind, ordinal in tables[kind].get(output) or ():
                    if input_kind == kind:
                        sources.add(ordinal)
                candidates = []
                for ordinal in sorted(sources):
                    candidates.extend(self.lookup(inputs[ordinal]))
                if not candidates:
                    candidates.extend(self.lookup(output))
                self.register(output, candidates, allow_partner=allow_partner)

        # Transport keeps a sketch label only where the same shape came
        # through. A merged output is a new shape whose maker answers
        # nothing, and the clean-up step is the measured case of that.
        self.carry_sketch_lineage(
            result,
            inputs_by_kind,
            tables,
            barrier,
            identity_tables=input_tables,
            strict=barrier is not None,
        )

    def capture(self, builder, result, operation, adapter, api_class):
        result = self.unwrap(result)
        if result.IsNull():
            return
        semantic = self.active_semantic()
        if semantic is not None:
            source_line, semantic_operation, semantic_api_class = semantic
            if adapter == "primitive":
                if semantic_operation == "LocationPattern":
                    self.capture_active_semantic_relation(
                        result,
                        source_line,
                        semantic_operation,
                        semantic_api_class,
                    )
                    return
                original_line = builder._cadmark_source_line
                builder._cadmark_source_line = source_line
                try:
                    self.capture_primitive(
                        builder, result, semantic_operation, semantic_api_class
                    )
                finally:
                    builder._cadmark_source_line = original_line
                return
            if adapter == "copy":
                if api_class == "BRepBuilderAPI_Copy":
                    self.capture_transport(builder, result, allow_partner=True)
                    return
                original_line = builder._cadmark_source_line
                builder._cadmark_source_line = source_line
                try:
                    self.capture_history(
                        builder,
                        result,
                        semantic_operation,
                        semantic_api_class,
                        allow_partner=True,
                    )
                finally:
                    builder._cadmark_source_line = original_line
                return
            if adapter == "history" and semantic_operation == "Mirror":
                self.capture_active_semantic_relation(
                    result, source_line, semantic_operation, semantic_api_class
                )
                return
        if adapter == "primitive":
            self.capture_primitive(builder, result, operation, api_class)
        elif adapter == "history":
            self.capture_history(builder, result, operation, api_class)
        elif adapter == "sweep":
            self.capture_sweep(builder, result, operation, api_class)
        elif adapter == "copy":
            self.capture_transport(builder, result, allow_partner=True)
        elif adapter == "cleanup":
            self.capture_transport(
                builder,
                result,
                allow_partner=False,
                barrier={"reason": "clean_up"},
            )

    def wrap(self, original, operation, adapter, api_class):
        session = self

        def init(instance, *args, **kwargs):
            instance._cadmark_source_line = session.user_line()
            instance._cadmark_inputs = session.collect_shapes((args, kwargs))
            instance._cadmark_captured = False
            original.__init__(instance, *args, **kwargs)

        namespace = {"__init__": init, "__module__": original.__module__}

        # Builders hand back their result through Shape() or, for some
        # primitives, Solid(); whichever is called first captures it.
        for accessor_name in _cadmark_result_methods:
            if not hasattr(original, accessor_name):
                continue
            original_accessor = getattr(original, accessor_name)

            def accessor(instance, *args, _accessor=original_accessor, **kwargs):
                result = _accessor(instance, *args, **kwargs)
                if not instance._cadmark_captured:
                    instance._cadmark_captured = True
                    session.capture(instance, result, operation, adapter, api_class)
                return result

            namespace[accessor_name] = accessor

        for method_name in _cadmark_input_methods:
            if not hasattr(original, method_name):
                continue
            original_method = getattr(original, method_name)

            def capture_input(instance, *args, _method=original_method, **kwargs):
                for captured in session.collect_shapes((args, kwargs)):
                    if not any(
                        captured.IsSame(existing)
                        for existing in instance._cadmark_inputs
                    ):
                        instance._cadmark_inputs.append(captured)
                return _method(instance, *args, **kwargs)

            namespace[method_name] = capture_input

        return type(api_class, (original,), namespace)

    def install_location_hook(self):
        module = _cadmark_importlib.import_module("build123d.build_common")
        session = self
        location_list = module.LocationList
        pattern_types = tuple(
            getattr(module, name)
            for name in ("Locations", "GridLocations", "PolarLocations", "HexLocations")
        )
        original_enter = location_list.__enter__
        original_exit = location_list.__exit__

        def enter(instance):
            is_pattern = isinstance(instance, pattern_types)
            if is_pattern:
                session.push_semantic(
                    session.user_line(), "LocationPattern", type(instance).__name__
                )
            try:
                return original_enter(instance)
            except Exception:
                if is_pattern:
                    session.pop_semantic()
                raise

        def exit(instance, exception_type, exception_value, traceback):
            is_pattern = isinstance(instance, pattern_types)
            try:
                return original_exit(instance, exception_type, exception_value, traceback)
            finally:
                if is_pattern:
                    session.pop_semantic()

        location_list.__enter__ = enter
        location_list.__exit__ = exit
        self.originals.append((location_list, "__enter__", original_enter))
        self.originals.append((location_list, "__exit__", original_exit))

    def install_transform_hook(self, method_name, operation):
        module = _cadmark_importlib.import_module("build123d.topology.shape_core")
        shape = module.Shape
        original = getattr(shape, method_name)
        session = self

        def transform(instance, *args, **kwargs):
            source_line = session.user_line()
            session.push_semantic(source_line, operation, method_name)
            try:
                result = original(instance, *args, **kwargs)
            finally:
                session.pop_semantic()
            is_location_only_rotate = (
                method_name == "rotate"
                and not kwargs.get("transform", args[2] if len(args) > 2 else False)
            )
            if is_location_only_rotate:
                session.capture_location_only_transform(
                    result, source_line, operation, method_name
                )
            return result

        setattr(shape, method_name, transform)
        self.originals.append((shape, method_name, original))

    def install_location_transport_hook(self):
        module = _cadmark_importlib.import_module("build123d.topology.shape_core")
        shape = module.Shape
        original = shape.moved
        session = self

        def moved(instance, *args, **kwargs):
            result = original(instance, *args, **kwargs)
            if (
                session.active_semantic() is None
                and session.has_location_only_transform(instance)
            ):
                session.capture_location_transport(instance, result)
            return result

        shape.moved = moved
        self.originals.append((shape, "moved", original))

    def install_generic_operation_hook(self, module_name, method_name, operation):
        """Record a build123d operation with no history-reporting maker.

        The operation's result is credited to the user line as Modified,
        and sketch labels move onto it only where an input's exact shape
        survived; every other output states the operation as the barrier
        the label could not cross.
        """
        module = _cadmark_importlib.import_module(module_name)
        build123d = _cadmark_importlib.import_module("build123d")
        original = getattr(module, method_name)
        exported = getattr(build123d, method_name, None)
        session = self

        def hooked(*args, **kwargs):
            source_line = session.user_line()
            inputs = session.collect_shapes((args, kwargs))
            session.push_semantic(source_line, operation, method_name)
            try:
                result = original(*args, **kwargs)
            finally:
                session.pop_semantic()
            session.capture_generic_operation(
                result, inputs, source_line, operation, method_name
            )
            return result

        setattr(module, method_name, hooked)
        self.originals.append((module, method_name, original))
        if exported is original:
            setattr(build123d, method_name, hooked)
            self.originals.append((build123d, method_name, exported))

    def capture_generic_operation(self, result, inputs, source_line, operation, api_class):
        shape = self.unwrap(result)
        if shape is None or not isinstance(shape, _cadmark_shape_type) or shape.IsNull():
            return
        # An instrumented maker inside the operation has usually claimed
        # everything it built under this semantic already (a 3D fillet's
        # own builder, say); the operation is recorded here only when
        # something it produced has no maker's word for it.
        unclaimed = [
            output
            for _kind, outputs in self.topology(shape)
            for output in outputs
            if not self.lookup(output)
        ]
        if not unclaimed:
            return
        operation_id = self.new_operation(source_line, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Modified"}
        inputs_by_kind = self.inputs_by_kind(inputs)
        input_tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}
        for kind, members in inputs_by_kind.items():
            for ordinal, member in enumerate(members):
                input_tables[kind].slot(member, lambda ordinal=ordinal: ordinal)
        empty_tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}
        for output in unclaimed:
            self.register(output, [candidate])
        self.carry_sketch_lineage(
            shape,
            inputs_by_kind,
            empty_tables,
            {"reason": "history_empty", "operation_id": operation_id},
            identity_tables=input_tables,
            strict=True,
        )

    def install_generic_mirror_hook(self):
        module = _cadmark_importlib.import_module("build123d.operations_generic")
        build123d = _cadmark_importlib.import_module("build123d")
        original = module.mirror
        original_export = build123d.mirror
        session = self

        def mirror(*args, **kwargs):
            session.push_semantic(session.user_line(), "Mirror", "mirror")
            try:
                return original(*args, **kwargs)
            finally:
                session.pop_semantic()

        module.mirror = mirror
        build123d.mirror = mirror
        self.originals.append((module, "mirror", original))
        self.originals.append((build123d, "mirror", original_export))

    def wrap_sketch_base(self, original_init):
        session = self

        def init(instance, *args, **kwargs):
            sketch_id = session.begin_sketch_object(instance, (args, kwargs))
            original_init(instance, *args, **kwargs)
            session.register_sketch_object(instance, sketch_id)

        return init

    def install_sketch_labelling(self, bases=None):
        bases = _cadmark_sketch_bases if bases is None else bases
        installed = []
        try:
            for module_name, attribute in bases:
                module = _cadmark_importlib.import_module(module_name)
                base = getattr(module, attribute)
                original_init = base.__init__
                base.__init__ = self.wrap_sketch_base(original_init)
                if base.__init__ is original_init:
                    raise ProvenanceWrapperError(
                        f"failed to label {module_name}.{attribute}"
                    )
                installed.append((base, original_init))
            self.sketch_originals = installed
        except Exception:
            for base, original_init in reversed(installed):
                base.__init__ = original_init
            raise

    def restore_sketch_labelling(self):
        failures = []
        for base, original_init in reversed(self.sketch_originals):
            try:
                base.__init__ = original_init
            except Exception:
                failures.append(base.__name__)
        self.sketch_originals = []
        return failures

    def install(self, manifest=None):
        manifest = _cadmark_manifest if manifest is None else manifest
        installed = []
        try:
            for module_name, attribute, expected, operation, adapter in manifest:
                module = _cadmark_importlib.import_module(module_name)
                original = getattr(module, attribute)
                if not isinstance(original, type) or not issubclass(original, expected):
                    raise ProvenanceWrapperError(
                        f"{module_name}.{attribute} is not the expected OCP base"
                    )
                wrapped = self.wrap(original, operation, adapter, attribute)
                setattr(module, attribute, wrapped)
                if getattr(module, attribute) is not wrapped:
                    raise ProvenanceWrapperError(
                        f"failed to replace {module_name}.{attribute}"
                    )
                installed.append((module, attribute, original))
            self.install_sketch_labelling()
            self.originals = installed
            self.install_location_hook()
            self.install_transform_hook("mirror", "Mirror")
            self.install_transform_hook("rotate", "Rotate")
            self.install_transform_hook("scale", "Scale")
            self.install_location_transport_hook()
            self.install_generic_mirror_hook()
            # Sketch operations whose makers keep no history: the result is
            # credited to the operation, and a drawn curve that did not
            # survive by identity states the operation as its barrier.
            self.install_generic_operation_hook("build123d.operations_generic", "fillet", "Fillet")
            self.install_generic_operation_hook("build123d.operations_sketch", "make_face", "MakeFace")
            self.install_generic_operation_hook("build123d.operations_sketch", "make_hull", "MakeFace")
        except Exception:
            originals = self.originals or installed
            for module, attribute, original in reversed(originals):
                setattr(module, attribute, original)
            self.originals = []
            raise

    def restore(self):
        failures = self.restore_sketch_labelling()
        for module, attribute, original in reversed(self.originals):
            try:
                setattr(module, attribute, original)
                if getattr(module, attribute) is not original:
                    failures.append(f"{module.__name__}.{attribute}")
            except Exception:
                failures.append(f"{module.__name__}.{attribute}")
        self.originals = []
        if failures:
            raise ProvenanceWrapperError(
                "failed to restore " + ", ".join(failures)
            )

    def finalise(self, shape):
        shape = self.unwrap(shape)
        self.final_maps = {
            kind: self.make_map(shape, _cadmark_kind_enum[kind])
            for kind in _cadmark_kinds
        }
        result = {
            "schema_version": 1,
            "operations": list(self.operations),
            "faces": [],
            "edges": [],
            "vertices": [],
            "tombstones": list(self.tombstones),
            "sketches": list(self.sketches),
        }
        for kind, output_name in (
            ("face", "faces"),
            ("edge", "edges"),
            ("vertex", "vertices"),
        ):
            for final_shape in self.map_values(self.final_maps[kind]):
                result[output_name].append(
                    {
                        "candidates": self.lookup(
                            final_shape, partner_fallback=True
                        ),
                        "sketch": self.sketch_state(final_shape),
                    }
                )
        return result

    def finalise_sketch(self, shape):
        """The sketch route of every element of a drawn profile.

        Elements are listed in the order of the profile's own indexed
        topology maps — the numbering the profile view draws and picks
        them under — so a clicked curve, corner or region resolves to the
        line that drew it, or to the stated reason none did.
        """
        shape = self.unwrap(shape)
        result = {
            "schema_version": 1,
            "operations": list(self.operations),
            "sketches": list(self.sketches),
        }
        for kind, output_name in (
            ("face", "regions"),
            ("edge", "curves"),
            ("vertex", "corners"),
        ):
            members = self.map_values(self.make_map(shape, _cadmark_kind_enum[kind]))
            result[output_name] = [
                {"sketch": self.sketch_state(member)} for member in members
            ]
        return result

    def topology_index(self, shape, kind):
        indexed = self.final_maps[kind]
        index = indexed.FindIndex(shape)
        if index == 0:
            raise UnsupportedProvenanceCapture(
                f"{kind} is absent from the final topology map"
            )
        return index - 1


def _cadmark_validate_runtime(actual=None):
    if actual is None:
        actual = (
            _cadmark_sys.version_info[:2],
            _cadmark_build123d.__version__,
            _cadmark_ocp.__version__,
            _cadmark_metadata.version("cadquery-ocp-novtk"),
        )
    expected = ((3, 12), "0.11.1", "7.9.3.1", "7.9.3.1.1")
    if actual != expected:
        raise UnsupportedRuntimeVersion(
            f"expected Python/build123d/OCP/distribution {expected}, got {actual}"
        )


def _cadmark_install(filename, manifest=None, actual_runtime=None):
    _cadmark_validate_runtime(actual_runtime)
    session = _CadmarkSession(filename)
    session.install(manifest)
    return session
