import importlib as _cadmark_importlib
import importlib.metadata as _cadmark_metadata
import inspect as _cadmark_inspect
import sys as _cadmark_sys

import OCP as _cadmark_ocp
import build123d as _cadmark_build123d
from OCP.BRepAlgoAPI import (
    BRepAlgoAPI_Common as _cadmark_expected_common,
    BRepAlgoAPI_Cut as _cadmark_expected_cut,
    BRepAlgoAPI_Fuse as _cadmark_expected_fuse,
    BRepAlgoAPI_Splitter as _cadmark_expected_splitter,
)
from OCP.BRepBuilderAPI import (
    BRepBuilderAPI_Copy as _cadmark_expected_copy,
    BRepBuilderAPI_GTransform as _cadmark_expected_gtransform,
    BRepBuilderAPI_Transform as _cadmark_expected_transform,
)
from OCP.BRepFeat import BRepFeat_MakeDPrism as _cadmark_expected_dprism
from OCP.BRepFilletAPI import (
    BRepFilletAPI_MakeChamfer as _cadmark_expected_chamfer,
    BRepFilletAPI_MakeFillet as _cadmark_expected_fillet,
)
from OCP.BRepOffset import BRepOffset_MakeOffset as _cadmark_expected_offset
from OCP.BRepOffsetAPI import (
    BRepOffsetAPI_DraftAngle as _cadmark_expected_draft,
    BRepOffsetAPI_MakePipeShell as _cadmark_expected_pipe,
    BRepOffsetAPI_MakeThickSolid as _cadmark_expected_thick,
    BRepOffsetAPI_ThruSections as _cadmark_expected_loft,
)
from OCP.BRepPrimAPI import (
    BRepPrimAPI_MakeBox as _cadmark_expected_box,
    BRepPrimAPI_MakeCone as _cadmark_expected_cone,
    BRepPrimAPI_MakeCylinder as _cadmark_expected_cylinder,
    BRepPrimAPI_MakePrism as _cadmark_expected_prism,
    BRepPrimAPI_MakeRevol as _cadmark_expected_revol,
    BRepPrimAPI_MakeSphere as _cadmark_expected_sphere,
    BRepPrimAPI_MakeTorus as _cadmark_expected_torus,
    BRepPrimAPI_MakeWedge as _cadmark_expected_wedge,
)
from OCP.LocOpe import LocOpe_DPrism as _cadmark_expected_taper
from OCP.ShapeUpgrade import (
    ShapeUpgrade_UnifySameDomain as _cadmark_expected_cleanup,
)
from OCP.TopAbs import (
    TopAbs_EDGE as _cadmark_edge,
    TopAbs_FACE as _cadmark_face,
    TopAbs_VERTEX as _cadmark_vertex,
)
from OCP.TopExp import TopExp as _cadmark_top_exp
from OCP.TopTools import TopTools_IndexedMapOfShape as _cadmark_indexed_map
from OCP.TopoDS import TopoDS_Shape as _cadmark_shape_type


class UnsupportedRuntimeVersion(RuntimeError):
    pass


class ProvenanceWrapperError(RuntimeError):
    pass


class UnsupportedProvenanceCapture(RuntimeError):
    pass


# Each entry: module holding the binding, OCP class name, the expected OCP
# base, the semantic operation credited to the user line (None for transport
# that carries existing provenance through unchanged), and the capture
# adapter. Adapters:
#   primitive - every output element is Generated by this operation
#   history   - the builder reports Generated/Modified per input element
#   sweep     - history, with anything left unattributed credited as Generated
#               (profiles from sketches survive into the result with no entry)
#   copy      - transport; partner identity is accepted for located copies
#   cleanup   - transport; distinct merged sources are kept as ambiguity
_cadmark_manifest = (
    ("build123d.topology.three_d", "BRepPrimAPI_MakeBox", _cadmark_expected_box, "Box", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCylinder", _cadmark_expected_cylinder, "Cylinder", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeSphere", _cadmark_expected_sphere, "Sphere", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeCone", _cadmark_expected_cone, "Cone", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeTorus", _cadmark_expected_torus, "Torus", "primitive"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeWedge", _cadmark_expected_wedge, "Wedge", "primitive"),
    ("build123d.topology.utils", "BRepPrimAPI_MakePrism", _cadmark_expected_prism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "LocOpe_DPrism", _cadmark_expected_taper, "Extrude", "primitive"),
    ("build123d.topology.three_d", "BRepFeat_MakeDPrism", _cadmark_expected_dprism, "Extrude", "sweep"),
    ("build123d.topology.three_d", "BRepPrimAPI_MakeRevol", _cadmark_expected_revol, "Revolve", "sweep"),
    ("build123d.topology.utils", "BRepOffsetAPI_ThruSections", _cadmark_expected_loft, "Loft", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakePipeShell", _cadmark_expected_pipe, "Sweep", "sweep"),
    ("build123d.topology.three_d", "BRepOffset_MakeOffset", _cadmark_expected_offset, "Thicken", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_MakeThickSolid", _cadmark_expected_thick, "Shell", "sweep"),
    ("build123d.topology.three_d", "BRepOffsetAPI_DraftAngle", _cadmark_expected_draft, "Draft", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Splitter", _cadmark_expected_splitter, "Split", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Fuse", _cadmark_expected_fuse, "BooleanFuse", "history"),
    ("build123d.topology.shape_core", "BRepAlgoAPI_Cut", _cadmark_expected_cut, "BooleanCut", "history"),
    ("build123d.topology.three_d", "BRepAlgoAPI_Common", _cadmark_expected_common, "BooleanCommon", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeFillet", _cadmark_expected_fillet, "Fillet", "history"),
    ("build123d.topology.three_d", "BRepFilletAPI_MakeChamfer", _cadmark_expected_chamfer, "Chamfer", "history"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Copy", _cadmark_expected_copy, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_Transform", _cadmark_expected_transform, None, "copy"),
    ("build123d.topology.shape_core", "BRepBuilderAPI_GTransform", _cadmark_expected_gtransform, None, "copy"),
    ("build123d.topology.shape_core", "ShapeUpgrade_UnifySameDomain", _cadmark_expected_cleanup, None, "cleanup"),
)

# Builder methods that receive input shapes after construction.
_cadmark_input_methods = (
    "SetArguments",
    "SetTools",
    "Add",
    "AddWire",
    "AddVertex",
    "Perform",
    "Initialize",
    "MakeThickSolidByJoin",
)

# Builder methods that return the finished result.
_cadmark_result_methods = ("Shape", "Solid")

_cadmark_kinds = ("face", "edge", "vertex")
_cadmark_kind_enum = {
    "face": _cadmark_face,
    "edge": _cadmark_edge,
    "vertex": _cadmark_vertex,
}
_cadmark_relation_priority = (
    "Generated",
    "Modified",
    "GeneratedDescendant",
    "ModifiedDescendant",
)


def _cadmark_unique_candidates(candidates):
    seen = set()
    result = []
    for candidate in candidates:
        key = (candidate["operation_id"], candidate["relation"])
        if key not in seen:
            seen.add(key)
            result.append(candidate)
    result.sort(key=lambda item: (item["operation_id"], item["relation"]))
    return result


class _CadmarkShapeTable:
    """Values keyed by shape identity (TShape and location, orientation ignored)."""

    def __init__(self):
        self.index = _cadmark_indexed_map()
        self.values = []

    def slot(self, shape, factory):
        position = self.index.Add(shape)
        if position > len(self.values):
            self.values.append(factory())
        return self.values[position - 1]

    def get(self, shape):
        position = self.index.FindIndex(shape)
        if position == 0:
            return None
        return self.values[position - 1]

    def __len__(self):
        return len(self.values)


class _CadmarkSession:
    def __init__(self, filename):
        self.filename = filename
        self.operations = []
        self.tombstones = []
        # shape -> {"candidates": [...], "allow_partner": bool}
        self.registry = _CadmarkShapeTable()
        # Located default-rotate results share a TShape with their retained
        # receiver, so only an explicit subsequent move may carry their
        # provenance to a new placement.
        self.location_only_transforms = _CadmarkShapeTable()
        self.originals = []
        self.final_maps = {}
        self._next_operation_id = 1
        self.semantic_stack = []

    def user_line(self):
        frame = _cadmark_inspect.currentframe()
        try:
            frame = frame.f_back
            while frame is not None:
                if frame.f_code.co_filename == self.filename:
                    return frame.f_lineno
                frame = frame.f_back
        finally:
            del frame
        raise UnsupportedProvenanceCapture(
            f"no user frame for provenance capture in {self.filename}"
        )

    @staticmethod
    def unwrap(value):
        if hasattr(value, "wrapped"):
            value = value.wrapped
        return value

    def collect_shapes(self, value):
        found = []

        def visit(item):
            item = self.unwrap(item)
            if isinstance(item, _cadmark_shape_type):
                found.append(item)
                return
            if isinstance(item, dict):
                for nested in item.values():
                    visit(nested)
                return
            if isinstance(item, (str, bytes)):
                return
            if isinstance(item, (tuple, list, set)):
                for nested in item:
                    visit(nested)
                return
            try:
                for nested in item:
                    visit(nested)
            except (TypeError, RuntimeError):
                return

        visit(value)
        unique = []
        for shape in found:
            if not any(shape.IsSame(existing) for existing in unique):
                unique.append(shape)
        return unique

    @staticmethod
    def make_map(shape, topology_kind):
        result = _cadmark_indexed_map()
        _cadmark_top_exp.MapShapes_s(shape, topology_kind, result)
        return result

    @staticmethod
    def map_values(indexed_map):
        return [indexed_map.FindKey(index) for index in range(1, indexed_map.Extent() + 1)]

    def topology(self, shape):
        return tuple(
            (kind, self.map_values(self.make_map(shape, _cadmark_kind_enum[kind])))
            for kind in _cadmark_kinds
        )

    @staticmethod
    def kind_of(shape):
        shape_type = shape.ShapeType()
        if shape_type == _cadmark_face:
            return "face"
        if shape_type == _cadmark_edge:
            return "edge"
        if shape_type == _cadmark_vertex:
            return "vertex"
        return None

    def inputs_by_kind(self, roots):
        """Every distinct face, edge and vertex of the input shapes."""
        maps = {kind: _cadmark_indexed_map() for kind in _cadmark_kinds}
        for root in roots:
            for kind in _cadmark_kinds:
                _cadmark_top_exp.MapShapes_s(root, _cadmark_kind_enum[kind], maps[kind])
        return {kind: self.map_values(maps[kind]) for kind in _cadmark_kinds}

    def lookup(self, shape, partner_fallback=False):
        record = self.registry.get(shape)
        candidates = list(record["candidates"]) if record else []
        if not candidates and partner_fallback:
            for record in self.registry.values:
                if record["allow_partner"] and shape.IsPartner(record["shape"]):
                    candidates.extend(record["candidates"])
        return _cadmark_unique_candidates(candidates)

    def register(self, shape, candidates, allow_partner=False, replace=False):
        candidates = _cadmark_unique_candidates(candidates)
        if not candidates:
            return
        record = self.registry.slot(
            shape,
            lambda: {"shape": shape, "candidates": [], "allow_partner": False},
        )
        if replace:
            record["candidates"] = candidates
            record["allow_partner"] = allow_partner
        else:
            record["candidates"] = _cadmark_unique_candidates(
                record["candidates"] + candidates
            )
            record["allow_partner"] = record["allow_partner"] or allow_partner

    def new_operation(self, source_line, operation, api_class):
        operation_id = self._next_operation_id
        self._next_operation_id += 1
        self.operations.append(
            {
                "operation_id": operation_id,
                "source_line": source_line,
                "operation": operation,
                "api_class": api_class,
            }
        )
        return operation_id

    def push_semantic(self, source_line, operation, api_class):
        self.semantic_stack.append((source_line, operation, api_class))

    def pop_semantic(self):
        self.semantic_stack.pop()

    def active_semantic(self):
        if self.semantic_stack:
            return self.semantic_stack[-1]
        return None

    @staticmethod
    def history_results(builder, method, shape):
        try:
            result = getattr(builder, method)(shape)
            return list(result)
        except (AttributeError, TypeError, RuntimeError):
            try:
                history = builder.History()
                result = getattr(history, method)(shape)
                return list(result)
            except (AttributeError, TypeError, RuntimeError):
                return []

    def history_table(self, builder, inputs_by_kind):
        """Index every shape the builder reports as changed, once per input.

        Returns one table per output kind. Each entry maps an output shape to
        the set of (relation, input kind, input ordinal) triples that reach
        it: a direct relation when the builder named the shape itself, a
        descendant relation when it named a shape containing it.
        """
        tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}

        def note(shape, kind, relation, input_kind, ordinal):
            tables[kind].slot(shape, set).add((relation, input_kind, ordinal))

        for input_kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                for relation in ("Generated", "Modified"):
                    for changed in self.history_results(builder, relation, input_shape):
                        changed_kind = self.kind_of(changed)
                        if changed_kind is not None:
                            note(changed, changed_kind, relation, input_kind, ordinal)
                        for kind, members in self.topology(changed):
                            for member in members:
                                if changed_kind == kind and member.IsSame(changed):
                                    continue
                                note(
                                    member,
                                    kind,
                                    relation + "Descendant",
                                    input_kind,
                                    ordinal,
                                )
        return tables

    @staticmethod
    def select_relation(relations):
        for relation in _cadmark_relation_priority:
            if relation in relations:
                return relation
        return None

    def capture_primitive(self, builder, result, operation, api_class):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, shapes in self.topology(result):
            for shape in shapes:
                self.register(
                    shape, [candidate], allow_partner=True, replace=True
                )

    def capture_location_only_transform(self, result, source_line, operation, api_class):
        operation_id = self.new_operation(source_line, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Modified"}
        for _kind, shapes in self.topology(self.unwrap(result)):
            for shape in shapes:
                self.location_only_transforms.slot(shape, lambda: True)
                self.register(shape, [candidate])

    def has_location_only_transform(self, shape):
        return any(
            self.location_only_transforms.get(member) is not None
            for _kind, members in self.topology(self.unwrap(shape))
            for member in members
        )

    def capture_location_transport(self, original, result):
        """Carry a located default-rotate result to one later placement.

        This is deliberately exact-location transport rather than partner
        fallback: the retained receiver has the same partner topology but was
        not rotated.
        """
        inputs_by_kind = dict(self.topology(self.unwrap(original)))
        for kind, outputs in self.topology(self.unwrap(result)):
            for output in outputs:
                candidates = []
                for input_shape in inputs_by_kind[kind]:
                    if output.IsPartner(input_shape):
                        candidates.extend(self.lookup(input_shape))
                self.register(output, candidates, replace=True)

    def capture_active_semantic_relation(self, result, source_line, operation, api_class):
        operation_id = self.new_operation(source_line, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Modified"}
        for _kind, shapes in self.topology(result):
            for shape in shapes:
                self.register(shape, [candidate], allow_partner=True, replace=True)

    def capture_history(self, builder, result, operation, api_class, allow_partner=False):
        operation_id = self.new_operation(
            builder._cadmark_source_line, operation, api_class
        )
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)

        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                try:
                    deleted = bool(builder.IsDeleted(input_shape))
                except (AttributeError, TypeError, RuntimeError):
                    deleted = False
                if deleted:
                    self.tombstones.append(
                        {
                            "operation_id": operation_id,
                            "kind": kind,
                            "ordinal": ordinal,
                        }
                    )

        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            for output in outputs:
                reached = tables[kind].get(output) or set()
                # Prefer history reported against inputs of the output's own
                # kind; fall back to what any input reports.
                same_kind = {
                    relation
                    for relation, input_kind, _ordinal in reached
                    if input_kind == kind
                }
                relations = same_kind or {relation for relation, _k, _o in reached}
                selected = self.select_relation(relations)
                if selected is not None:
                    self.register(
                        output,
                        [{"operation_id": operation_id, "relation": selected}],
                        allow_partner=allow_partner,
                        replace=True,
                    )
        return operation_id

    def capture_sweep(self, builder, result, operation, api_class):
        # A sweep (prism, revolve, loft, pipe, offset) reports the topology it
        # generates from each profile element, but the profile itself survives
        # as the base of the result with no history entry. The profile usually
        # comes from a sketch, which is outside the instrumented set, so any
        # output the history left unattributed is credited to the sweep as
        # Generated.
        operation_id = self.capture_history(builder, result, operation, api_class)
        candidate = {"operation_id": operation_id, "relation": "Generated"}
        for _kind, outputs in self.topology(result):
            for output in outputs:
                if not self.lookup(output):
                    self.register(output, [candidate])

    def capture_transport(self, builder, result, allow_partner):
        inputs_by_kind = self.inputs_by_kind(builder._cadmark_inputs)
        input_tables = {kind: _CadmarkShapeTable() for kind in _cadmark_kinds}
        for kind, inputs in inputs_by_kind.items():
            for ordinal, input_shape in enumerate(inputs):
                input_tables[kind].slot(input_shape, lambda ordinal=ordinal: ordinal)
        tables = self.history_table(builder, inputs_by_kind)
        for kind, outputs in self.topology(result):
            inputs = inputs_by_kind[kind]
            for output in outputs:
                sources = set()
                same = input_tables[kind].get(output)
                if same is not None:
                    sources.add(same)
                for _relation, input_kind, ordinal in tables[kind].get(output) or ():
                    if input_kind == kind:
                        sources.add(ordinal)
                candidates = []
                for ordinal in sorted(sources):
                    candidates.extend(self.lookup(inputs[ordinal]))
                if not candidates:
                    candidates.extend(self.lookup(output))
                self.register(output, candidates, allow_partner=allow_partner)

    def capture(self, builder, result, operation, adapter, api_class):
        result = self.unwrap(result)
        if result.IsNull():
            return
        semantic = self.active_semantic()
        if semantic is not None:
            source_line, semantic_operation, semantic_api_class = semantic
            if adapter == "primitive":
                if semantic_operation == "LocationPattern":
                    self.capture_active_semantic_relation(
                        result,
                        source_line,
                        semantic_operation,
                        semantic_api_class,
                    )
                    return
                original_line = builder._cadmark_source_line
                builder._cadmark_source_line = source_line
                try:
                    self.capture_primitive(
                        builder, result, semantic_operation, semantic_api_class
                    )
                finally:
                    builder._cadmark_source_line = original_line
                return
            if adapter == "copy":
                if api_class == "BRepBuilderAPI_Copy":
                    self.capture_transport(builder, result, allow_partner=True)
                    return
                original_line = builder._cadmark_source_line
                builder._cadmark_source_line = source_line
                try:
                    self.capture_history(
                        builder,
                        result,
                        semantic_operation,
                        semantic_api_class,
                        allow_partner=True,
                    )
                finally:
                    builder._cadmark_source_line = original_line
                return
            if adapter == "history" and semantic_operation == "Mirror":
                self.capture_active_semantic_relation(
                    result, source_line, semantic_operation, semantic_api_class
                )
                return
        if adapter == "primitive":
            self.capture_primitive(builder, result, operation, api_class)
        elif adapter == "history":
            self.capture_history(builder, result, operation, api_class)
        elif adapter == "sweep":
            self.capture_sweep(builder, result, operation, api_class)
        elif adapter == "copy":
            self.capture_transport(builder, result, allow_partner=True)
        elif adapter == "cleanup":
            self.capture_transport(builder, result, allow_partner=False)

    def wrap(self, original, operation, adapter, api_class):
        session = self

        def init(instance, *args, **kwargs):
            instance._cadmark_source_line = session.user_line()
            instance._cadmark_inputs = session.collect_shapes((args, kwargs))
            instance._cadmark_captured = False
            original.__init__(instance, *args, **kwargs)

        namespace = {"__init__": init, "__module__": original.__module__}

        # Builders hand back their result through Shape() or, for some
        # primitives, Solid(); whichever is called first captures it.
        for accessor_name in _cadmark_result_methods:
            if not hasattr(original, accessor_name):
                continue
            original_accessor = getattr(original, accessor_name)

            def accessor(instance, *args, _accessor=original_accessor, **kwargs):
                result = _accessor(instance, *args, **kwargs)
                if not instance._cadmark_captured:
                    instance._cadmark_captured = True
                    session.capture(instance, result, operation, adapter, api_class)
                return result

            namespace[accessor_name] = accessor

        for method_name in _cadmark_input_methods:
            if not hasattr(original, method_name):
                continue
            original_method = getattr(original, method_name)

            def capture_input(instance, *args, _method=original_method, **kwargs):
                for captured in session.collect_shapes((args, kwargs)):
                    if not any(
                        captured.IsSame(existing)
                        for existing in instance._cadmark_inputs
                    ):
                        instance._cadmark_inputs.append(captured)
                return _method(instance, *args, **kwargs)

            namespace[method_name] = capture_input

        return type(api_class, (original,), namespace)

    def install_location_hook(self):
        module = _cadmark_importlib.import_module("build123d.build_common")
        session = self
        location_list = module.LocationList
        pattern_types = tuple(
            getattr(module, name)
            for name in ("Locations", "GridLocations", "PolarLocations", "HexLocations")
        )
        original_enter = location_list.__enter__
        original_exit = location_list.__exit__

        def enter(instance):
            is_pattern = isinstance(instance, pattern_types)
            if is_pattern:
                session.push_semantic(
                    session.user_line(), "LocationPattern", type(instance).__name__
                )
            try:
                return original_enter(instance)
            except Exception:
                if is_pattern:
                    session.pop_semantic()
                raise

        def exit(instance, exception_type, exception_value, traceback):
            is_pattern = isinstance(instance, pattern_types)
            try:
                return original_exit(instance, exception_type, exception_value, traceback)
            finally:
                if is_pattern:
                    session.pop_semantic()

        location_list.__enter__ = enter
        location_list.__exit__ = exit
        self.originals.append((location_list, "__enter__", original_enter))
        self.originals.append((location_list, "__exit__", original_exit))

    def install_transform_hook(self, method_name, operation):
        module = _cadmark_importlib.import_module("build123d.topology.shape_core")
        shape = module.Shape
        original = getattr(shape, method_name)
        session = self

        def transform(instance, *args, **kwargs):
            source_line = session.user_line()
            session.push_semantic(source_line, operation, method_name)
            try:
                result = original(instance, *args, **kwargs)
            finally:
                session.pop_semantic()
            is_location_only_rotate = (
                method_name == "rotate"
                and not kwargs.get("transform", args[2] if len(args) > 2 else False)
            )
            if is_location_only_rotate:
                session.capture_location_only_transform(
                    result, source_line, operation, method_name
                )
            return result

        setattr(shape, method_name, transform)
        self.originals.append((shape, method_name, original))

    def install_location_transport_hook(self):
        module = _cadmark_importlib.import_module("build123d.topology.shape_core")
        shape = module.Shape
        original = shape.moved
        session = self

        def moved(instance, *args, **kwargs):
            result = original(instance, *args, **kwargs)
            if (
                session.active_semantic() is None
                and session.has_location_only_transform(instance)
            ):
                session.capture_location_transport(instance, result)
            return result

        shape.moved = moved
        self.originals.append((shape, "moved", original))

    def install_generic_mirror_hook(self):
        module = _cadmark_importlib.import_module("build123d.operations_generic")
        build123d = _cadmark_importlib.import_module("build123d")
        original = module.mirror
        original_export = build123d.mirror
        session = self

        def mirror(*args, **kwargs):
            session.push_semantic(session.user_line(), "Mirror", "mirror")
            try:
                return original(*args, **kwargs)
            finally:
                session.pop_semantic()

        module.mirror = mirror
        build123d.mirror = mirror
        self.originals.append((module, "mirror", original))
        self.originals.append((build123d, "mirror", original_export))

    def install(self, manifest=None):
        manifest = _cadmark_manifest if manifest is None else manifest
        installed = []
        try:
            for module_name, attribute, expected, operation, adapter in manifest:
                module = _cadmark_importlib.import_module(module_name)
                original = getattr(module, attribute)
                if not isinstance(original, type) or not issubclass(original, expected):
                    raise ProvenanceWrapperError(
                        f"{module_name}.{attribute} is not the expected OCP base"
                    )
                wrapped = self.wrap(original, operation, adapter, attribute)
                setattr(module, attribute, wrapped)
                if getattr(module, attribute) is not wrapped:
                    raise ProvenanceWrapperError(
                        f"failed to replace {module_name}.{attribute}"
                    )
                installed.append((module, attribute, original))
            self.originals = installed
            self.install_location_hook()
            self.install_transform_hook("mirror", "Mirror")
            self.install_transform_hook("rotate", "Rotate")
            self.install_transform_hook("scale", "Scale")
            self.install_location_transport_hook()
            self.install_generic_mirror_hook()
        except Exception:
            originals = self.originals or installed
            for module, attribute, original in reversed(originals):
                setattr(module, attribute, original)
            self.originals = []
            raise

    def restore(self):
        failures = []
        for module, attribute, original in reversed(self.originals):
            try:
                setattr(module, attribute, original)
                if getattr(module, attribute) is not original:
                    failures.append(f"{module.__name__}.{attribute}")
            except Exception:
                failures.append(f"{module.__name__}.{attribute}")
        self.originals = []
        if failures:
            raise ProvenanceWrapperError(
                "failed to restore " + ", ".join(failures)
            )

    def finalise(self, shape):
        shape = self.unwrap(shape)
        self.final_maps = {
            kind: self.make_map(shape, _cadmark_kind_enum[kind])
            for kind in _cadmark_kinds
        }
        result = {
            "schema_version": 1,
            "operations": list(self.operations),
            "faces": [],
            "edges": [],
            "vertices": [],
            "tombstones": list(self.tombstones),
        }
        for kind, output_name in (
            ("face", "faces"),
            ("edge", "edges"),
            ("vertex", "vertices"),
        ):
            for final_shape in self.map_values(self.final_maps[kind]):
                result[output_name].append(
                    {
                        "candidates": self.lookup(
                            final_shape, partner_fallback=True
                        )
                    }
                )
        return result

    def topology_index(self, shape, kind):
        indexed = self.final_maps[kind]
        index = indexed.FindIndex(shape)
        if index == 0:
            raise UnsupportedProvenanceCapture(
                f"{kind} is absent from the final topology map"
            )
        return index - 1


def _cadmark_validate_runtime(actual=None):
    if actual is None:
        actual = (
            _cadmark_sys.version_info[:2],
            _cadmark_build123d.__version__,
            _cadmark_ocp.__version__,
            _cadmark_metadata.version("cadquery-ocp-novtk"),
        )
    expected = ((3, 12), "0.11.1", "7.9.3.1", "7.9.3.1.1")
    if actual != expected:
        raise UnsupportedRuntimeVersion(
            f"expected Python/build123d/OCP/distribution {expected}, got {actual}"
        )


def _cadmark_install(filename, manifest=None, actual_runtime=None):
    _cadmark_validate_runtime(actual_runtime)
    session = _CadmarkSession(filename)
    session.install(manifest)
    return session
