[package]
name = "cadmark-renderer"
version.workspace = true
edition = "2024"

[dependencies]
cadmark-core = { workspace = true }
cadmark-kernel = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
