[package]
name = "cadmark-app"
version.workspace = true
edition = "2024"

[[bin]]
name = "cadmark"
path = "src/main.rs"

[dependencies]
cadmark-core = { workspace = true }
cadmark-kernel = { workspace = true }
cadmark-renderer = { workspace = true }
cadmark-ui = { workspace = true }
cadmark-bridge = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
png = "=0.18.1"
rfd = { version = "0.17.2", default-features = false, features = ["xdg-portal", "wayland"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
open = "=5.4.2"

[dev-dependencies]
tempfile = { workspace = true }
