// Provenance ledger — maps rendered geometry to generating code.
//
// Transient at runtime; rebuilt by re-executing the build123d script.
// Each entry links a topological element to the source line that created it.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::geometry::{EdgeId, FaceId, VertexId};

/// A reference to a line in the build123d script.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SourceRef {
    /// 1-indexed line number in the script.
    pub line: u32,
    /// The source code text at that line.
    pub code: String,
}

/// Records how a topological element relates to its generating operation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProvenanceKind {
    /// Directly created by the operation.
    Generated,
    /// Existed before and was modified by the operation.
    Modified,
}

/// A single provenance record linking an element to its generating code.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceEntry {
    pub source: SourceRef,
    pub kind: ProvenanceKind,
}

/// The provenance ledger — rebuilt each time the script executes.
///
/// Maps each topological element (face, edge, vertex) to the source line
/// that generated or last modified it. When an element has been through
/// multiple operations (e.g. a face created by a Box then modified by a
/// Fillet), the most recent operation is stored.
#[derive(Debug, Default)]
pub struct ProvenanceLedger {
    faces: HashMap<FaceId, ProvenanceEntry>,
    edges: HashMap<EdgeId, ProvenanceEntry>,
    vertices: HashMap<VertexId, ProvenanceEntry>,
}

impl ProvenanceLedger {
    pub fn new() -> Self {
        Self::default()
    }

    /// Clear the ledger for a fresh script execution.
    pub fn clear(&mut self) {
        self.faces.clear();
        self.edges.clear();
        self.vertices.clear();
    }

    // -- Face provenance --

    pub fn record_face(&mut self, id: FaceId, entry: ProvenanceEntry) {
        self.faces.insert(id, entry);
    }

    pub fn lookup_face(&self, id: FaceId) -> Option<&ProvenanceEntry> {
        self.faces.get(&id)
    }

    // -- Edge provenance --

    pub fn record_edge(&mut self, id: EdgeId, entry: ProvenanceEntry) {
        self.edges.insert(id, entry);
    }

    pub fn lookup_edge(&self, id: EdgeId) -> Option<&ProvenanceEntry> {
        self.edges.get(&id)
    }

    // -- Vertex provenance --

    pub fn record_vertex(&mut self, id: VertexId, entry: ProvenanceEntry) {
        self.vertices.insert(id, entry);
    }

    pub fn lookup_vertex(&self, id: VertexId) -> Option<&ProvenanceEntry> {
        self.vertices.get(&id)
    }

    /// Total number of entries across all element types.
    pub fn len(&self) -> usize {
        self.faces.len() + self.edges.len() + self.vertices.len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source(line: u32, code: &str) -> SourceRef {
        SourceRef {
            line,
            code: code.to_string(),
        }
    }

    #[test]
    fn record_and_lookup_face() {
        let mut ledger = ProvenanceLedger::new();
        let id = FaceId(0);
        let entry = ProvenanceEntry {
            source: source(5, "box = Box(10, 10, 10)"),
            kind: ProvenanceKind::Generated,
        };
        ledger.record_face(id, entry.clone());

        let found = ledger.lookup_face(id).unwrap();
        assert_eq!(found.source.line, 5);
        assert_eq!(found.kind, ProvenanceKind::Generated);
    }

    #[test]
    fn modification_overwrites_generation() {
        let mut ledger = ProvenanceLedger::new();
        let id = FaceId(3);

        // Initially generated by Box.
        ledger.record_face(
            id,
            ProvenanceEntry {
                source: source(2, "box = Box(10, 10, 10)"),
                kind: ProvenanceKind::Generated,
            },
        );

        // Then modified by Fillet — overwrites.
        ledger.record_face(
            id,
            ProvenanceEntry {
                source: source(3, "fillet = Fillet(box, 1.0)"),
                kind: ProvenanceKind::Modified,
            },
        );

        let found = ledger.lookup_face(id).unwrap();
        assert_eq!(found.source.line, 3);
        assert_eq!(found.kind, ProvenanceKind::Modified);
    }

    #[test]
    fn clear_empties_all() {
        let mut ledger = ProvenanceLedger::new();
        ledger.record_face(
            FaceId(0),
            ProvenanceEntry {
                source: source(1, "x"),
                kind: ProvenanceKind::Generated,
            },
        );
        ledger.record_edge(
            EdgeId(0),
            ProvenanceEntry {
                source: source(1, "x"),
                kind: ProvenanceKind::Generated,
            },
        );
        assert_eq!(ledger.len(), 2);

        ledger.clear();
        assert!(ledger.is_empty());
    }

    #[test]
    fn lookup_missing_returns_none() {
        let ledger = ProvenanceLedger::new();
        assert!(ledger.lookup_face(FaceId(999)).is_none());
        assert!(ledger.lookup_edge(EdgeId(999)).is_none());
        assert!(ledger.lookup_vertex(VertexId(999)).is_none());
    }
}
