[package]
name = "cadmark-kernel"
version.workspace = true
edition = "2024"

[dependencies]
cadmark-core = { workspace = true }
pyo3 = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
cadmark-bridge = { workspace = true }
